# Generated by Django 5.0.6 on 2024-06-10 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('datum_narozeni', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Novela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('datum_vydani', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novely', to='novel.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Recenze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obsah', models.TextField()),
                ('hodnoceni', models.IntegerField()),
                ('datum_recenzovani', models.DateField(auto_now_add=True)),
                ('novela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenze', to='novel.novela')),
            ],
        ),
    ]
